/* =========================================================================
   A QR code, drawn here rather than fetched.

   WHY THIS IS HAND-WRITTEN
   The Content-Security-Policy allows scripts from ourselves and Cloudflare's
   challenge host, and nothing else. Pulling a QR library from a CDN would
   mean widening that policy for every page in the product so one dialog can
   draw a square - a bad trade, and the CSP exists because we were serving
   the repository to the internet three days ago.

   SCOPE, DELIBERATELY NARROW
   Byte mode, error-correction level M, versions 1 to 7. That covers up to
   122 characters, and the longest thing this draws is an upload URL of
   about ninety-five. Every version here has UNIFORM error-correction
   blocks, which removes the whole class of interleaving bugs that the
   mixed-block versions (8 and up) invite. If something longer ever needs a
   code, add the version and its table rather than guessing.

   Level M corrects about 15% of the symbol. That is the right level for a
   screen held up across a counter and photographed at an angle by a phone
   that is not quite steady.

   VERIFICATION
   A QR that does not scan is worse than no QR, and nothing in this file can
   prove one scans. test/qr.test.js reads the modules back out - unmasking,
   reading the format bits, un-interleaving, and parsing the byte-mode
   payload - and asserts it recovers the exact string. That catches every
   mistake except a misunderstanding shared by both halves, which is why the
   last check is still somebody pointing a phone at it.
   ========================================================================= */
(function () {
  'use strict';

  /* ---------------------------------------------------------- GF(256) --- */
  /* QR arithmetic happens in the field generated by x^8+x^4+x^3+x^2+1. */
  const EXP = new Uint8Array(512);
  const LOG = new Uint8Array(256);
  (function buildTables() {
    let x = 1;
    for (let i = 0; i < 255; i++) {
      EXP[i] = x;
      LOG[x] = i;
      x <<= 1;
      if (x & 0x100) x ^= 0x11D;
    }
    for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
  })();

  const mul = (a, b) => (a === 0 || b === 0) ? 0 : EXP[LOG[a] + LOG[b]];

  /* The generator polynomial for `count` error-correction codewords. */
  function generator(count) {
    let poly = [1];
    for (let i = 0; i < count; i++) {
      const next = new Array(poly.length + 1).fill(0);
      for (let j = 0; j < poly.length; j++) {
        next[j] ^= poly[j];
        next[j + 1] ^= mul(poly[j], EXP[i]);
      }
      poly = next;
    }
    return poly;
  }

  /* Remainder of data / generator - the error-correction codewords. */
  function ecCodewords(data, count) {
    const gen = generator(count);
    const buffer = [...data, ...new Array(count).fill(0)];
    for (let i = 0; i < data.length; i++) {
      const lead = buffer[i];
      if (!lead) continue;
      for (let j = 0; j < gen.length; j++) buffer[i + j] ^= mul(gen[j], lead);
    }
    return buffer.slice(data.length);
  }

  /* ------------------------------------------------------ the versions --- */
  /* Level M only, and only versions whose blocks are all the same size.
     [ total codewords, data codewords, blocks, alignment centres ] */
  const VERSIONS = {
    1: { total: 26,  data: 16,  blocks: 1, align: [] },
    2: { total: 44,  data: 28,  blocks: 1, align: [6, 18] },
    3: { total: 70,  data: 44,  blocks: 1, align: [6, 22] },
    4: { total: 100, data: 64,  blocks: 2, align: [6, 26] },
    5: { total: 134, data: 86,  blocks: 2, align: [6, 30] },
    6: { total: 172, data: 108, blocks: 4, align: [6, 34] },
    7: { total: 196, data: 124, blocks: 4, align: [6, 22, 38] }
  };

  const sizeOf = version => version * 4 + 17;

  /* Byte mode: 4 bits of mode, then the length, then the bytes. Versions up
     to 9 use an 8-bit length, so every version here does. */
  const capacityChars = version => VERSIONS[version].data - 2;

  function pickVersion(byteLength) {
    for (let version = 1; version <= 7; version++) {
      if (byteLength <= capacityChars(version)) return version;
    }
    return null;
  }

  /* ------------------------------------------------------- the payload --- */

  function encodeData(bytes, version) {
    const spec = VERSIONS[version];
    const bits = [];
    const push = (value, length) => {
      for (let i = length - 1; i >= 0; i--) bits.push((value >> i) & 1);
    };

    push(0b0100, 4);          /* byte mode */
    push(bytes.length, 8);    /* character count */
    for (const byte of bytes) push(byte, 8);

    /* Terminator, then pad to a byte boundary. */
    const capacityBits = spec.data * 8;
    for (let i = 0; i < 4 && bits.length < capacityBits; i++) bits.push(0);
    while (bits.length % 8) bits.push(0);

    const codewords = [];
    for (let i = 0; i < bits.length; i += 8) {
      codewords.push(parseInt(bits.slice(i, i + 8).join(''), 2));
    }
    /* The two pad bytes the specification names, alternating. */
    const PADS = [0xEC, 0x11];
    let pad = 0;
    while (codewords.length < spec.data) codewords.push(PADS[pad++ % 2]);

    /* Split into blocks, compute EC for each, then interleave - data
       codewords first, taking one from each block in turn, then the EC
       codewords the same way. */
    const perBlock = spec.data / spec.blocks;
    const ecPerBlock = (spec.total - spec.data) / spec.blocks;
    const dataBlocks = [];
    const ecBlocks = [];
    for (let b = 0; b < spec.blocks; b++) {
      const block = codewords.slice(b * perBlock, (b + 1) * perBlock);
      dataBlocks.push(block);
      ecBlocks.push(ecCodewords(block, ecPerBlock));
    }

    const out = [];
    for (let i = 0; i < perBlock; i++) {
      for (const block of dataBlocks) out.push(block[i]);
    }
    for (let i = 0; i < ecPerBlock; i++) {
      for (const block of ecBlocks) out.push(block[i]);
    }
    return out;
  }

  /* -------------------------------------------------------- the matrix --- */

  /* null means "not yet placed" - which is also what marks a module as
     free for data, so function patterns must all be written first. */
  function blankMatrix(size) {
    return Array.from({ length: size }, () => new Array(size).fill(null));
  }

  function placeFinder(matrix, row, col) {
    for (let r = -1; r <= 7; r++) {
      for (let c = -1; c <= 7; c++) {
        const y = row + r, x = col + c;
        if (y < 0 || x < 0 || y >= matrix.length || x >= matrix.length) continue;
        const onRing = (r >= 0 && r <= 6 && (c === 0 || c === 6)) ||
                       (c >= 0 && c <= 6 && (r === 0 || r === 6));
        const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
        matrix[y][x] = (onRing || inCore) ? 1 : 0;
      }
    }
  }

  function placeFunctionPatterns(matrix, version) {
    const size = matrix.length;
    placeFinder(matrix, 0, 0);
    placeFinder(matrix, 0, size - 7);
    placeFinder(matrix, size - 7, 0);

    /* Timing patterns. */
    for (let i = 8; i < size - 8; i++) {
      const bit = i % 2 === 0 ? 1 : 0;
      matrix[6][i] = bit;
      matrix[i][6] = bit;
    }

    /* Alignment patterns, skipping the three that would sit on a finder. */
    const centres = VERSIONS[version].align;
    for (const r of centres) {
      for (const c of centres) {
        const onFinder = (r <= 8 && c <= 8) ||
          (r <= 8 && c >= size - 9) || (r >= size - 9 && c <= 8);
        if (onFinder) continue;
        for (let dr = -2; dr <= 2; dr++) {
          for (let dc = -2; dc <= 2; dc++) {
            const ring = Math.max(Math.abs(dr), Math.abs(dc));
            matrix[r + dr][c + dc] = (ring === 1) ? 0 : 1;
          }
        }
      }
    }

    /* The one module that is always dark. */
    matrix[size - 8][8] = 1;

    /* Reserve the format areas so data placement skips them. */
    for (let i = 0; i <= 8; i++) {
      if (matrix[8][i] === null) matrix[8][i] = 0;
      if (matrix[i][8] === null) matrix[i][8] = 0;
    }
    for (let i = 0; i < 8; i++) {
      if (matrix[8][size - 1 - i] === null) matrix[8][size - 1 - i] = 0;
      if (matrix[size - 1 - i][8] === null) matrix[size - 1 - i][8] = 0;
    }

    /* Version information, from version 7 upwards. */
    if (version >= 7) {
      for (let i = 0; i < 18; i++) {
        const r = Math.floor(i / 3), c = i % 3;
        matrix[size - 11 + c][r] = 0;
        matrix[r][size - 11 + c] = 0;
      }
    }
  }

  /* Which modules data may occupy: the ones still null after the function
     patterns are written. */
  function dataMask(matrix) {
    return matrix.map(row => row.map(cell => cell === null));
  }

  function placeData(matrix, free, codewords) {
    const size = matrix.length;
    const bits = [];
    for (const byte of codewords) {
      for (let i = 7; i >= 0; i--) bits.push((byte >> i) & 1);
    }

    let index = 0, upward = true;
    for (let right = size - 1; right > 0; right -= 2) {
      /* Column 6 is the vertical timing pattern and is not a data column. */
      if (right === 6) right = 5;
      for (let step = 0; step < size; step++) {
        const row = upward ? size - 1 - step : step;
        for (const col of [right, right - 1]) {
          if (!free[row][col]) continue;
          matrix[row][col] = index < bits.length ? bits[index] : 0;
          index++;
        }
      }
      upward = !upward;
    }
  }

  const MASKS = [
    (r, c) => (r + c) % 2 === 0,
    (r) => r % 2 === 0,
    (r, c) => c % 3 === 0,
    (r, c) => (r + c) % 3 === 0,
    (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
    (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
    (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
    (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0
  ];

  function applyMask(matrix, free, mask) {
    const out = matrix.map(row => [...row]);
    for (let r = 0; r < out.length; r++) {
      for (let c = 0; c < out.length; c++) {
        if (free[r][c] && MASKS[mask](r, c)) out[r][c] ^= 1;
      }
    }
    return out;
  }

  /* The four penalty rules. A reader copes better with a symbol that has
     fewer long runs, fewer solid blocks and a balanced amount of dark. */
  function penalty(matrix) {
    const size = matrix.length;
    let score = 0;

    const runScore = line => {
      let total = 0, run = 1;
      for (let i = 1; i < line.length; i++) {
        if (line[i] === line[i - 1]) { run++; continue; }
        if (run >= 5) total += 3 + (run - 5);
        run = 1;
      }
      if (run >= 5) total += 3 + (run - 5);
      return total;
    };
    for (let i = 0; i < size; i++) {
      score += runScore(matrix[i]);
      score += runScore(matrix.map(row => row[i]));
    }

    for (let r = 0; r < size - 1; r++) {
      for (let c = 0; c < size - 1; c++) {
        const v = matrix[r][c];
        if (v === matrix[r][c + 1] && v === matrix[r + 1][c] && v === matrix[r + 1][c + 1]) {
          score += 3;
        }
      }
    }

    /* The finder-like sequence, in both directions. */
    const PATTERN = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
    const REVERSE = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
    const hasAt = (line, at, pattern) =>
      pattern.every((bit, i) => line[at + i] === bit);
    for (let i = 0; i < size; i++) {
      const row = matrix[i];
      const col = matrix.map(r => r[i]);
      for (let j = 0; j + 11 <= size; j++) {
        if (hasAt(row, j, PATTERN) || hasAt(row, j, REVERSE)) score += 40;
        if (hasAt(col, j, PATTERN) || hasAt(col, j, REVERSE)) score += 40;
      }
    }

    let dark = 0;
    for (const row of matrix) for (const cell of row) dark += cell;
    const percent = (dark * 100) / (size * size);
    score += Math.floor(Math.abs(percent - 50) / 5) * 10;

    return score;
  }

  /* Format information: two bits of EC level (M = 00), three of mask,
     BCH(15,5), then XOR with the fixed mask the specification names. */
  function formatBits(mask) {
    const data = (0b00 << 3) | mask;
    let value = data << 10;
    for (let i = 4; i >= 0; i--) {
      if (value & (1 << (i + 10))) value ^= 0b10100110111 << i;
    }
    return ((data << 10) | value) ^ 0b101010000010010;
  }

  function placeFormat(matrix, mask) {
    const size = matrix.length;
    const bits = formatBits(mask);
    const bit = i => (bits >> i) & 1;

    for (let i = 0; i <= 5; i++) matrix[8][i] = bit(i);
    matrix[8][7] = bit(6);
    matrix[8][8] = bit(7);
    matrix[7][8] = bit(8);
    for (let i = 9; i <= 14; i++) matrix[14 - i][8] = bit(i);

    for (let i = 0; i <= 7; i++) matrix[size - 1 - i][8] = bit(i);
    for (let i = 8; i <= 14; i++) matrix[8][size - 15 + i] = bit(i);
    matrix[size - 8][8] = 1;
  }

  function placeVersion(matrix, version) {
    if (version < 7) return;
    const size = matrix.length;
    let value = version << 12;
    for (let i = 5; i >= 0; i--) {
      if (value & (1 << (i + 12))) value ^= 0b1111100100101 << i;
    }
    const bits = (version << 12) | value;
    for (let i = 0; i < 18; i++) {
      const bit = (bits >> i) & 1;
      const r = Math.floor(i / 3), c = i % 3;
      matrix[size - 11 + c][r] = bit;
      matrix[r][size - 11 + c] = bit;
    }
  }

  /* ----------------------------------------------------------- public --- */

  /* Returns { size, modules } where modules[row][col] is 1 for dark. */
  function encode(text) {
    const bytes = [...new TextEncoder().encode(String(text))];
    const version = pickVersion(bytes.length);
    if (!version) {
      throw new Error('That is too long for a version 7 code (' +
        bytes.length + ' bytes, limit ' + capacityChars(7) + ').');
    }

    const size = sizeOf(version);
    const matrix = blankMatrix(size);
    placeFunctionPatterns(matrix, version);
    const free = dataMask(matrix);
    placeData(matrix, free, encodeData(bytes, version));

    let best = null;
    for (let mask = 0; mask < 8; mask++) {
      const candidate = applyMask(matrix, free, mask);
      placeFormat(candidate, mask);
      placeVersion(candidate, version);
      const score = penalty(candidate);
      if (!best || score < best.score) best = { score, mask, modules: candidate };
    }

    return { size, version, mask: best.mask, modules: best.modules };
  }

  /* An SVG, because it stays sharp when a doctor zooms in on a laptop and
     when a phone camera is held at an angle. `quiet` is the mandatory light
     border - a code without it is much harder to read against a page. */
  function svg(text, { scale = 8, quiet = 4 } = {}) {
    const { size, modules } = encode(text);
    const total = (size + quiet * 2) * scale;
    let path = '';
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        if (!modules[r][c]) continue;
        path += 'M' + ((c + quiet) * scale) + ' ' + ((r + quiet) * scale) +
          'h' + scale + 'v' + scale + 'h-' + scale + 'z';
      }
    }
    return '<svg xmlns="http://www.w3.org/2000/svg" width="' + total + '" height="' + total +
      '" viewBox="0 0 ' + total + ' ' + total + '" role="img" aria-label="QR code">' +
      '<rect width="' + total + '" height="' + total + '" fill="#fff"/>' +
      '<path d="' + path + '" fill="#000"/></svg>';
  }

  const api = { encode, svg, capacity: capacityChars(7) };
  if (typeof window !== 'undefined') window.TCOSQr = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})();
