/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceLabRouteImport } from './routes/experience-lab'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Demo3dRouteImport } from './routes/demo.3d'
import { Route as DemoCinematicRouteImport } from './routes/demo.cinematic'
import { Route as DemoDynamicRouteImport } from './routes/demo.dynamic'
import { Route as DemoEssentialRouteImport } from './routes/demo.essential'
import { Route as DemoInteractiveRouteImport } from './routes/demo.interactive'
import { Route as DemoPlatformRouteImport } from './routes/demo.platform'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as WebsiteStudioIndexRouteImport } from './routes/website-studio.index'
import { Route as WebsiteStudioSlugRouteImport } from './routes/website-studio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLabRoute = ExperienceLabRouteImport.update({
  id: '/experience-lab',
  path: '/experience-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo3dRoute = Demo3dRouteImport.update({
  id: '/demo/3d',
  path: '/demo/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCinematicRoute = DemoCinematicRouteImport.update({
  id: '/demo/cinematic',
  path: '/demo/cinematic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDynamicRoute = DemoDynamicRouteImport.update({
  id: '/demo/dynamic',
  path: '/demo/dynamic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEssentialRoute = DemoEssentialRouteImport.update({
  id: '/demo/essential',
  path: '/demo/essential',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInteractiveRoute = DemoInteractiveRouteImport.update({
  id: '/demo/interactive',
  path: '/demo/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlatformRoute = DemoPlatformRouteImport.update({
  id: '/demo/platform',
  path: '/demo/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteStudioIndexRoute = WebsiteStudioIndexRouteImport.update({
  id: '/website-studio/',
  path: '/website-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteStudioSlugRoute = WebsiteStudioSlugRouteImport.update({
  id: '/website-studio/$slug',
  path: '/website-studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/website-studio/': typeof WebsiteStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/website-studio': typeof WebsiteStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/website-studio/': typeof WebsiteStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/website-studio/$slug'
    | '/industries/'
    | '/portfolio/'
    | '/website-studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/website-studio/$slug'
    | '/industries'
    | '/portfolio'
    | '/website-studio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/portfolio/$slug'
    | '/website-studio/$slug'
    | '/industries/'
    | '/portfolio/'
    | '/website-studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceLabRoute: typeof ExperienceLabRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRoute
  StartProjectRoute: typeof StartProjectRoute
  TermsRoute: typeof TermsRoute
  Demo3dRoute: typeof Demo3dRoute
  DemoCinematicRoute: typeof DemoCinematicRoute
  DemoDynamicRoute: typeof DemoDynamicRoute
  DemoEssentialRoute: typeof DemoEssentialRoute
  DemoInteractiveRoute: typeof DemoInteractiveRoute
  DemoPlatformRoute: typeof DemoPlatformRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  WebsiteStudioSlugRoute: typeof WebsiteStudioSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  WebsiteStudioIndexRoute: typeof WebsiteStudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-lab': {
      id: '/experience-lab'
      path: '/experience-lab'
      fullPath: '/experience-lab'
      preLoaderRoute: typeof ExperienceLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/3d': {
      id: '/demo/3d'
      path: '/demo/3d'
      fullPath: '/demo/3d'
      preLoaderRoute: typeof Demo3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cinematic': {
      id: '/demo/cinematic'
      path: '/demo/cinematic'
      fullPath: '/demo/cinematic'
      preLoaderRoute: typeof DemoCinematicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dynamic': {
      id: '/demo/dynamic'
      path: '/demo/dynamic'
      fullPath: '/demo/dynamic'
      preLoaderRoute: typeof DemoDynamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/essential': {
      id: '/demo/essential'
      path: '/demo/essential'
      fullPath: '/demo/essential'
      preLoaderRoute: typeof DemoEssentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/interactive': {
      id: '/demo/interactive'
      path: '/demo/interactive'
      fullPath: '/demo/interactive'
      preLoaderRoute: typeof DemoInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/platform': {
      id: '/demo/platform'
      path: '/demo/platform'
      fullPath: '/demo/platform'
      preLoaderRoute: typeof DemoPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-studio/': {
      id: '/website-studio/'
      path: '/website-studio'
      fullPath: '/website-studio/'
      preLoaderRoute: typeof WebsiteStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-studio/$slug': {
      id: '/website-studio/$slug'
      path: '/website-studio/$slug'
      fullPath: '/website-studio/$slug'
      preLoaderRoute: typeof WebsiteStudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceLabRoute: ExperienceLabRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRoute,
  StartProjectRoute: StartProjectRoute,
  TermsRoute: TermsRoute,
  Demo3dRoute: Demo3dRoute,
  DemoCinematicRoute: DemoCinematicRoute,
  DemoDynamicRoute: DemoDynamicRoute,
  DemoEssentialRoute: DemoEssentialRoute,
  DemoInteractiveRoute: DemoInteractiveRoute,
  DemoPlatformRoute: DemoPlatformRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  WebsiteStudioSlugRoute: WebsiteStudioSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  WebsiteStudioIndexRoute: WebsiteStudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
