/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ExperienceLabRouteImport } from './routes/experience-lab'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StartProjectRouteImport } from './routes/start-project'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Demo3dRouteImport } from './routes/demo.3d'
import { Route as DemoCinematicRouteImport } from './routes/demo.cinematic'
import { Route as DemoDynamicRouteImport } from './routes/demo.dynamic'
import { Route as DemoEssentialRouteImport } from './routes/demo.essential'
import { Route as DemoInteractiveRouteImport } from './routes/demo.interactive'
import { Route as DemoPlatformRouteImport } from './routes/demo.platform'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as LiveDemosIndexRouteImport } from './routes/live-demos.index'
import { Route as LiveDemosAutomationRouteImport } from './routes/live-demos.automation'
import { Route as LiveDemosBusinessSoftwareRouteImport } from './routes/live-demos.business-software'
import { Route as LiveDemosMobileAppsRouteImport } from './routes/live-demos.mobile-apps'
import { Route as LiveDemosWebsitesRouteImport } from './routes/live-demos.websites'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase.index'
import { Route as ShowcaseAutomationRouteImport } from './routes/showcase.automation'
import { Route as ShowcaseBusinessSoftwareRouteImport } from './routes/showcase.business-software'
import { Route as ShowcaseDashboardsRouteImport } from './routes/showcase.dashboards'
import { Route as ShowcaseMobileAppsRouteImport } from './routes/showcase.mobile-apps'
import { Route as ShowcaseWebsitesRouteImport } from './routes/showcase.websites'
import { Route as WebsiteStudioIndexRouteImport } from './routes/website-studio.index'
import { Route as WebsiteStudioSlugRouteImport } from './routes/website-studio.$slug'
import { Route as ShowcaseTemplatesSlugRouteImport } from './routes/showcase.templates.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceLabRoute = ExperienceLabRouteImport.update({
  id: '/experience-lab',
  path: '/experience-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StartProjectRoute = StartProjectRouteImport.update({
  id: '/start-project',
  path: '/start-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Demo3dRoute = Demo3dRouteImport.update({
  id: '/demo/3d',
  path: '/demo/3d',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCinematicRoute = DemoCinematicRouteImport.update({
  id: '/demo/cinematic',
  path: '/demo/cinematic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDynamicRoute = DemoDynamicRouteImport.update({
  id: '/demo/dynamic',
  path: '/demo/dynamic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEssentialRoute = DemoEssentialRouteImport.update({
  id: '/demo/essential',
  path: '/demo/essential',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoInteractiveRoute = DemoInteractiveRouteImport.update({
  id: '/demo/interactive',
  path: '/demo/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPlatformRoute = DemoPlatformRouteImport.update({
  id: '/demo/platform',
  path: '/demo/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemosIndexRoute = LiveDemosIndexRouteImport.update({
  id: '/live-demos/',
  path: '/live-demos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemosAutomationRoute = LiveDemosAutomationRouteImport.update({
  id: '/live-demos/automation',
  path: '/live-demos/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemosBusinessSoftwareRoute =
  LiveDemosBusinessSoftwareRouteImport.update({
    id: '/live-demos/business-software',
    path: '/live-demos/business-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const LiveDemosMobileAppsRoute = LiveDemosMobileAppsRouteImport.update({
  id: '/live-demos/mobile-apps',
  path: '/live-demos/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveDemosWebsitesRoute = LiveDemosWebsitesRouteImport.update({
  id: '/live-demos/websites',
  path: '/live-demos/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseAutomationRoute = ShowcaseAutomationRouteImport.update({
  id: '/showcase/automation',
  path: '/showcase/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseBusinessSoftwareRoute =
  ShowcaseBusinessSoftwareRouteImport.update({
    id: '/showcase/business-software',
    path: '/showcase/business-software',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShowcaseDashboardsRoute = ShowcaseDashboardsRouteImport.update({
  id: '/showcase/dashboards',
  path: '/showcase/dashboards',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseMobileAppsRoute = ShowcaseMobileAppsRouteImport.update({
  id: '/showcase/mobile-apps',
  path: '/showcase/mobile-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseWebsitesRoute = ShowcaseWebsitesRouteImport.update({
  id: '/showcase/websites',
  path: '/showcase/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteStudioIndexRoute = WebsiteStudioIndexRouteImport.update({
  id: '/website-studio/',
  path: '/website-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteStudioSlugRoute = WebsiteStudioSlugRouteImport.update({
  id: '/website-studio/$slug',
  path: '/website-studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseTemplatesSlugRoute = ShowcaseTemplatesSlugRouteImport.update({
  id: '/showcase/templates/$slug',
  path: '/showcase/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/live-demos/automation': typeof LiveDemosAutomationRoute
  '/live-demos/business-software': typeof LiveDemosBusinessSoftwareRoute
  '/live-demos/mobile-apps': typeof LiveDemosMobileAppsRoute
  '/live-demos/websites': typeof LiveDemosWebsitesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/showcase/automation': typeof ShowcaseAutomationRoute
  '/showcase/business-software': typeof ShowcaseBusinessSoftwareRoute
  '/showcase/dashboards': typeof ShowcaseDashboardsRoute
  '/showcase/mobile-apps': typeof ShowcaseMobileAppsRoute
  '/showcase/websites': typeof ShowcaseWebsitesRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/live-demos/': typeof LiveDemosIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/website-studio/': typeof WebsiteStudioIndexRoute
  '/showcase/templates/$slug': typeof ShowcaseTemplatesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/live-demos/automation': typeof LiveDemosAutomationRoute
  '/live-demos/business-software': typeof LiveDemosBusinessSoftwareRoute
  '/live-demos/mobile-apps': typeof LiveDemosMobileAppsRoute
  '/live-demos/websites': typeof LiveDemosWebsitesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/showcase/automation': typeof ShowcaseAutomationRoute
  '/showcase/business-software': typeof ShowcaseBusinessSoftwareRoute
  '/showcase/dashboards': typeof ShowcaseDashboardsRoute
  '/showcase/mobile-apps': typeof ShowcaseMobileAppsRoute
  '/showcase/websites': typeof ShowcaseWebsitesRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/live-demos': typeof LiveDemosIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/website-studio': typeof WebsiteStudioIndexRoute
  '/showcase/templates/$slug': typeof ShowcaseTemplatesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/experience-lab': typeof ExperienceLabRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/solutions': typeof SolutionsRoute
  '/start-project': typeof StartProjectRoute
  '/terms': typeof TermsRoute
  '/demo/3d': typeof Demo3dRoute
  '/demo/cinematic': typeof DemoCinematicRoute
  '/demo/dynamic': typeof DemoDynamicRoute
  '/demo/essential': typeof DemoEssentialRoute
  '/demo/interactive': typeof DemoInteractiveRoute
  '/demo/platform': typeof DemoPlatformRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/live-demos/automation': typeof LiveDemosAutomationRoute
  '/live-demos/business-software': typeof LiveDemosBusinessSoftwareRoute
  '/live-demos/mobile-apps': typeof LiveDemosMobileAppsRoute
  '/live-demos/websites': typeof LiveDemosWebsitesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/showcase/automation': typeof ShowcaseAutomationRoute
  '/showcase/business-software': typeof ShowcaseBusinessSoftwareRoute
  '/showcase/dashboards': typeof ShowcaseDashboardsRoute
  '/showcase/mobile-apps': typeof ShowcaseMobileAppsRoute
  '/showcase/websites': typeof ShowcaseWebsitesRoute
  '/website-studio/$slug': typeof WebsiteStudioSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/live-demos/': typeof LiveDemosIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/website-studio/': typeof WebsiteStudioIndexRoute
  '/showcase/templates/$slug': typeof ShowcaseTemplatesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/live-demos/automation'
    | '/live-demos/business-software'
    | '/live-demos/mobile-apps'
    | '/live-demos/websites'
    | '/portfolio/$slug'
    | '/showcase/automation'
    | '/showcase/business-software'
    | '/showcase/dashboards'
    | '/showcase/mobile-apps'
    | '/showcase/websites'
    | '/website-studio/$slug'
    | '/industries/'
    | '/live-demos/'
    | '/portfolio/'
    | '/showcase/'
    | '/website-studio/'
    | '/showcase/templates/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/live-demos/automation'
    | '/live-demos/business-software'
    | '/live-demos/mobile-apps'
    | '/live-demos/websites'
    | '/portfolio/$slug'
    | '/showcase/automation'
    | '/showcase/business-software'
    | '/showcase/dashboards'
    | '/showcase/mobile-apps'
    | '/showcase/websites'
    | '/website-studio/$slug'
    | '/industries'
    | '/live-demos'
    | '/portfolio'
    | '/showcase'
    | '/website-studio'
    | '/showcase/templates/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/experience-lab'
    | '/pricing'
    | '/privacy'
    | '/solutions'
    | '/start-project'
    | '/terms'
    | '/demo/3d'
    | '/demo/cinematic'
    | '/demo/dynamic'
    | '/demo/essential'
    | '/demo/interactive'
    | '/demo/platform'
    | '/industries/$slug'
    | '/live-demos/automation'
    | '/live-demos/business-software'
    | '/live-demos/mobile-apps'
    | '/live-demos/websites'
    | '/portfolio/$slug'
    | '/showcase/automation'
    | '/showcase/business-software'
    | '/showcase/dashboards'
    | '/showcase/mobile-apps'
    | '/showcase/websites'
    | '/website-studio/$slug'
    | '/industries/'
    | '/live-demos/'
    | '/portfolio/'
    | '/showcase/'
    | '/website-studio/'
    | '/showcase/templates/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ExperienceLabRoute: typeof ExperienceLabRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SolutionsRoute: typeof SolutionsRoute
  StartProjectRoute: typeof StartProjectRoute
  TermsRoute: typeof TermsRoute
  Demo3dRoute: typeof Demo3dRoute
  DemoCinematicRoute: typeof DemoCinematicRoute
  DemoDynamicRoute: typeof DemoDynamicRoute
  DemoEssentialRoute: typeof DemoEssentialRoute
  DemoInteractiveRoute: typeof DemoInteractiveRoute
  DemoPlatformRoute: typeof DemoPlatformRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  LiveDemosAutomationRoute: typeof LiveDemosAutomationRoute
  LiveDemosBusinessSoftwareRoute: typeof LiveDemosBusinessSoftwareRoute
  LiveDemosMobileAppsRoute: typeof LiveDemosMobileAppsRoute
  LiveDemosWebsitesRoute: typeof LiveDemosWebsitesRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ShowcaseAutomationRoute: typeof ShowcaseAutomationRoute
  ShowcaseBusinessSoftwareRoute: typeof ShowcaseBusinessSoftwareRoute
  ShowcaseDashboardsRoute: typeof ShowcaseDashboardsRoute
  ShowcaseMobileAppsRoute: typeof ShowcaseMobileAppsRoute
  ShowcaseWebsitesRoute: typeof ShowcaseWebsitesRoute
  WebsiteStudioSlugRoute: typeof WebsiteStudioSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  LiveDemosIndexRoute: typeof LiveDemosIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  WebsiteStudioIndexRoute: typeof WebsiteStudioIndexRoute
  ShowcaseTemplatesSlugRoute: typeof ShowcaseTemplatesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience-lab': {
      id: '/experience-lab'
      path: '/experience-lab'
      fullPath: '/experience-lab'
      preLoaderRoute: typeof ExperienceLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-project': {
      id: '/start-project'
      path: '/start-project'
      fullPath: '/start-project'
      preLoaderRoute: typeof StartProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/3d': {
      id: '/demo/3d'
      path: '/demo/3d'
      fullPath: '/demo/3d'
      preLoaderRoute: typeof Demo3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/cinematic': {
      id: '/demo/cinematic'
      path: '/demo/cinematic'
      fullPath: '/demo/cinematic'
      preLoaderRoute: typeof DemoCinematicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/dynamic': {
      id: '/demo/dynamic'
      path: '/demo/dynamic'
      fullPath: '/demo/dynamic'
      preLoaderRoute: typeof DemoDynamicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/essential': {
      id: '/demo/essential'
      path: '/demo/essential'
      fullPath: '/demo/essential'
      preLoaderRoute: typeof DemoEssentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/interactive': {
      id: '/demo/interactive'
      path: '/demo/interactive'
      fullPath: '/demo/interactive'
      preLoaderRoute: typeof DemoInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/platform': {
      id: '/demo/platform'
      path: '/demo/platform'
      fullPath: '/demo/platform'
      preLoaderRoute: typeof DemoPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos/': {
      id: '/live-demos/'
      path: '/live-demos'
      fullPath: '/live-demos/'
      preLoaderRoute: typeof LiveDemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos/automation': {
      id: '/live-demos/automation'
      path: '/live-demos/automation'
      fullPath: '/live-demos/automation'
      preLoaderRoute: typeof LiveDemosAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos/business-software': {
      id: '/live-demos/business-software'
      path: '/live-demos/business-software'
      fullPath: '/live-demos/business-software'
      preLoaderRoute: typeof LiveDemosBusinessSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos/mobile-apps': {
      id: '/live-demos/mobile-apps'
      path: '/live-demos/mobile-apps'
      fullPath: '/live-demos/mobile-apps'
      preLoaderRoute: typeof LiveDemosMobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-demos/websites': {
      id: '/live-demos/websites'
      path: '/live-demos/websites'
      fullPath: '/live-demos/websites'
      preLoaderRoute: typeof LiveDemosWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/automation': {
      id: '/showcase/automation'
      path: '/showcase/automation'
      fullPath: '/showcase/automation'
      preLoaderRoute: typeof ShowcaseAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/business-software': {
      id: '/showcase/business-software'
      path: '/showcase/business-software'
      fullPath: '/showcase/business-software'
      preLoaderRoute: typeof ShowcaseBusinessSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/dashboards': {
      id: '/showcase/dashboards'
      path: '/showcase/dashboards'
      fullPath: '/showcase/dashboards'
      preLoaderRoute: typeof ShowcaseDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/mobile-apps': {
      id: '/showcase/mobile-apps'
      path: '/showcase/mobile-apps'
      fullPath: '/showcase/mobile-apps'
      preLoaderRoute: typeof ShowcaseMobileAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/websites': {
      id: '/showcase/websites'
      path: '/showcase/websites'
      fullPath: '/showcase/websites'
      preLoaderRoute: typeof ShowcaseWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-studio/': {
      id: '/website-studio/'
      path: '/website-studio'
      fullPath: '/website-studio/'
      preLoaderRoute: typeof WebsiteStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-studio/$slug': {
      id: '/website-studio/$slug'
      path: '/website-studio/$slug'
      fullPath: '/website-studio/$slug'
      preLoaderRoute: typeof WebsiteStudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/templates/$slug': {
      id: '/showcase/templates/$slug'
      path: '/showcase/templates/$slug'
      fullPath: '/showcase/templates/$slug'
      preLoaderRoute: typeof ShowcaseTemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ExperienceLabRoute: ExperienceLabRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SolutionsRoute: SolutionsRoute,
  StartProjectRoute: StartProjectRoute,
  TermsRoute: TermsRoute,
  Demo3dRoute: Demo3dRoute,
  DemoCinematicRoute: DemoCinematicRoute,
  DemoDynamicRoute: DemoDynamicRoute,
  DemoEssentialRoute: DemoEssentialRoute,
  DemoInteractiveRoute: DemoInteractiveRoute,
  DemoPlatformRoute: DemoPlatformRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  LiveDemosAutomationRoute: LiveDemosAutomationRoute,
  LiveDemosBusinessSoftwareRoute: LiveDemosBusinessSoftwareRoute,
  LiveDemosMobileAppsRoute: LiveDemosMobileAppsRoute,
  LiveDemosWebsitesRoute: LiveDemosWebsitesRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ShowcaseAutomationRoute: ShowcaseAutomationRoute,
  ShowcaseBusinessSoftwareRoute: ShowcaseBusinessSoftwareRoute,
  ShowcaseDashboardsRoute: ShowcaseDashboardsRoute,
  ShowcaseMobileAppsRoute: ShowcaseMobileAppsRoute,
  ShowcaseWebsitesRoute: ShowcaseWebsitesRoute,
  WebsiteStudioSlugRoute: WebsiteStudioSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  LiveDemosIndexRoute: LiveDemosIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  WebsiteStudioIndexRoute: WebsiteStudioIndexRoute,
  ShowcaseTemplatesSlugRoute: ShowcaseTemplatesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
